# Website Settings
title: "Michelle Miller"
description: "Software Engineer"

repository: chellimiller.github.io/chellimiller.github.io

# Build Settings
markdown: kramdown
theme: jekyll-theme-slate
exclude: [README.md]
